name: Build/release master

on:
  push:
    branches: [ master ]

jobs:

  build:

    name: Build ARTOS operating system

    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Rollback release if exists
      uses: author/action-rollback@stable
      continue-on-error: true
      with:
        tag: dev_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      run: docker build -t docker.pkg.github.com/armkit/artos/artos:latest .

    - name: Publish docker image
      run: docker push docker.pkg.github.com/armkit/artos/artos:latest

  release:

    name: Release ARTOS-${{ matrix.sys }} image (${{ matrix.fmt }})

    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        sys: [virt]
        fmt: [exe, efi]

    steps:
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract files from docker
      run: docker run -v `pwd`:/wd -t docker.pkg.github.com/armkit/artos/artos:latest sh -c 'cp /artos/build/${{ matrix.sys }}/*.${{ matrix.fmt }} /wd'

    - name: Get artifact name
      run: echo 'FILE_NAME='`ls *.${{ matrix.fmt }}` >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILE_NAME }}
        path: ${{ env.FILE_NAME }}

    - name: Release artifact
      id: create_release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev_release
        name: Development Release
        draft: false
        prerelease: false
        files: ${{ env.FILE_NAME }}
        allow_override: true
